common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use common\models\Profile;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $password;

    const STATUS_DELETED = 0;
    const STATUS_BLOCKED = 5;
    const STATUS_ACTIVE = 10;

    const ROLE_DOCTOR = 5;
    const ROLE_ADMIN = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_BLOCKED],
            ['role', 'default', 'value' => self::ROLE_DOCTOR],
            //['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_BLOCKED]],
            [['role', 'status'], 'integer'],
            [['email'], 'email'],
            [['username'], 'string'],
            //[['created_date'], 'date', 'format' => 'php:m/d/Y'],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function attributeLabels(){
        return [
            'username' => 'Логин',
            'status'   => 'Статус',
            'role'     => 'Роль пользователя',
            'created_at' => 'Создан',
            'updated_at' => 'Обновлен',
        ];
    }

    public function roleArray(){
        return [
           ['id' => self::ROLE_ADMIN, 'name' => 'Администратор'],
           ['id' => self::ROLE_DOCTOR, 'name' => 'Врач'],
        ];
    }

    public function statusArray(){
        return [
            ['id' => self::STATUS_BLOCKED,  'name' => 'Да'],
            ['id' => self::STATUS_ACTIVE,   'name' => 'Нет'],
        ];
    }

    public function attrStrStatus($data){
        if($data->status == 10){
            return 'Активен';
        }else{
            return 'Заблокирован';
        }
    }

    public function attrStrRole($data){
        if($data->role == 5){
            return 'Врач';
        }else{
            return 'Администратор';
        }
    }

    /**
    * @return \yii\db\ActiveQuery
    */
    public function getProfile()
    {
        return $this->hasMany(Profile::className(), ['user_id' => 'id']);
    }
}

backend/controllers/ProfileController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\Profile;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/*
 * Profile controller
 */

class ProfileController extends Controller{

    protected function batchUpdate($items){
        if(Model::loadMultiple($items, Yii::$app->request->post()) && Model::validateMultiple($items)){
            foreach($items as $key => $item){
                $item->save();
            }
        }
    }

    /**
     * Finds the Profile model
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Profile the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($model = Profile::findOne($id)) !== null ){
            return $model;
        }else{
            throw new NotFoundHttpException('The request page does not exist.');
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findUser($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUpdate($userId){
        $user = $this->findUser($userId);
        $this->batchUpdate($user->profile);
        return $this->renderAjax('_profile', ['model' => $user]);
    }

    public function actionCreate(){
        //$user = $this->findUser($userId);
        $model = new Profile;
        $model->addOne();
        //$user->link('profile', $model); // link сохраняет в БД без валидации
        return $this->renderAjax('_profile', ['model' => $model]);
    }

   /* public function actionDelete($id){
        $model = $this->findModel($id);
        $user = $model->user;
        $model->delete();
        return $this->renderAjax('_profile');
    }*/
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->renderAjax('_profile');
    }

    /**
     * @inheritdoc
     */
    public function behaviors(){
        return [
            'access' => [
              'class' => AccessControl::className(),
              'rules' => [
                  [
                    'actions' => ['create', 'update', 'delete'],
                    'allow'  => true,
                    'roles'   => ['@'],
                  ],
              ]
            ],
        ];
    }

}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\Profile;
use common\models\UserSearch;
use yii\base\ErrorException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\Kladr;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $profile = new Profile();
        $model->setPassword($model->password);
        $model->generateAuthKey();

        if ($model->load(Yii::$app->request->post())) {
            if($model->validate()){
                if($model->save()){
                    $profile->user_id = $model->id;
                    $profile->save();
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'profile' => $profile,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $profile = $this->findProfile($id);

        if ($model->load(Yii::$app->request->post())) {
            if($model->validate()){
                $listStatus = $_POST['User']['status'];
                /*if(!empty($listStatus)) {
                    foreach ($listStatus as $value) {
                        $model->status = $value;
                    }
                }*/
                $model->save();
                //$profile->save();
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'profile' => $profile,
            ]);
        }
    }

    public function actionKladr(){
        // Инициализация api, в качестве параметров указываем токен и ключ для доступа к сервису
        $api = new Api('51dfe5d42fb2b43e3300006e', '86a2c2a06f1b2451a87d05512cc2c3edfdf41969');

        // Формирование запроса
        $query = new Kladr\Query();
        $query->ContentName = 'Арх';
        $query->ContentType = Kladr\ObjectType::City;
        $query->WithParent = true;
        $query->Limit = 2;

        // Получение данных в виде ассоциативного массива
        $arResult = $api->QueryToArray($query);
        var_dump($arResult); die();
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Страница пользователя не найдена.');
        }
    }
    protected function findProfile($id)
    {
        if($model = Profile::find()->where(['user_id' => $id])->one()) :
            if (($model) !== null) {
                return $model;
            }else {
                throw new NotFoundHttpException('Данные профиля пользователя не найдены.');
            }
        endif;
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'username')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <?php if(Yii::$app->controller->route == 'user/create') : ?>
        <?= $form->field($model, 'password')->passwordInput() ?>
    <?php endif; ?>

    <?= $form->field($model, 'role')->dropDownList(ArrayHelper::map($model->roleArray(), 'id', 'name')) ?>

    <?= $form->field($model, 'status')->dropDownList(ArrayHelper::map($model->statusArray(), 'id', 'name') )->label('Заблокировать') ?>

    <?php if(!empty($profile)) : ?>
        <?php if(Yii::$app->controller->route == 'user/update') : ?>
            <h2>Регистрационные данные врача</h2>

            <?= $form->field($profile, 'secondname')->textInput() ?>

            <?= $form->field($profile, 'firstname')->textInput() ?>

            <?= $form->field($profile, 'thirdname')->textInput() ?>

            <?= $form->field($profile, 'region')->textInput() ?>

            <?= $form->field($profile, 'city')->textInput() ?>

            <?= $form->field($profile, 'institution')->textInput() ?>

            <?= $form->field($profile, 'phonenumber')->textInput() ?>

        <?php endif; ?>
    <?php endif; ?>

    <?php if(Yii::$app->controller->route == 'user/create') :
        Pjax::begin(['enablePushState' => false]) ?>
        <?= Html::a('Добавить форму врача', Url::toRoute(['profile/create']), ['class' => 'btn btn-success', 'style' => 'margin-bottom: 15px'] ) ?>
        <?php Pjax::end();
    endif; ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin([
        'action' => Url::toRoute(['profile/update', 'userId' => $model->id]),
        'options' => [
            'data-pjax' => '1',
        ],
        'id' => 'profileUpdateForm',
    ]); ?>


    <?php foreach ($model->profile as $key => $profile): ?>
        <?= $form->field($profile, "[$key]firstname") ?>
        <?= $form->field($profile, "[$key]secondname") ?>
    <?php endforeach ?>

    <?= Html::a('Добавить форму профиля', Url::toRoute(['profile/create', 'userId' => $model->id]), ['class' => 'btn btn-success add-form-profile']); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'role') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Добавить нового пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить нового пользователя', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'username',
            'email:email',
            [
                'attribute' => 'role',
                'value'     => function($model){
                    if($model->role == 5){
                        return 'Врач';
                    }else{
                        return 'Администратор';
                    }
                }
            ],
            [
                'attribute' => 'status',
                'value'     => function($model){
                    if($model->status == 10){
                        return 'Активен';
                    }else{
                        return 'Заблокирован';
                    }
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/user/update.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Редактировать данные пользователя: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'profile' => $profile,
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Просмотр пользователя: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы точно хотите удалить пользователя?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'formatter'  => [
            'class'  => 'yii\i18n\Formatter',
            'dateFormat' => 'php:d.m.Y',
            'locale' => 'ru',
        ],
        'attributes' => [
            'username',
            'email:email',
            [
                'label' => 'Роль пользователя',
                'value' => $model->attrStrRole($model),
            ],
            [
                'label' => 'Статус',
                'value' => $model->attrStrStatus($model),
            ],
            'created_at:date',
            'updated_at:date',
        ],
    ]); ?>

</div>